"""first migrate

Revision ID: 450c8ee337eb
Revises: 
Create Date: 2021-06-06 14:54:51.561052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450c8ee337eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppy',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppy')
    # ### end Alembic commands ###
